# Generated by Django 4.1.7 on 2023-09-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_categories_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='Listings',
            field=models.ManyToManyField(blank=True, to='auctions.listing'),
        ),
    ]
