# Generated by Django 4.1.7 on 2023-09-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_categories_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='ListImagesUrl',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
