# Generated by Django 4.1.7 on 2023-10-03 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_listimagesurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='ListPrice',
            field=models.CharField(default=1, max_length=20), # type: ignore
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidAmount', models.IntegerField(max_length=10)),
                ('BidOnThisList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BidOnThisList', to='auctions.listing')),
                ('BidUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BidUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='ListBid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ListBid', to='auctions.bid'),
        ),
    ]
