# Generated by Django 4.2.5 on 2023-10-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='updated_at',
        ),
    ]
