# Generated by Django 4.1.7 on 2023-10-07 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='ListWatchList',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
