# Generated by Django 4.1.7 on 2023-11-11 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listing_listwatchlist_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionClosed', models.BooleanField(default=True)),
                ('HaigestBider', models.CharField(max_length=20)),
                ('ClosedList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ClosedList', to='auctions.listing')),
                ('HaigestBiderwoner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HaigestBider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
