# Generated by Django 4.1.7 on 2023-11-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_closedactions_actionclosed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='ListImagesUrl',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
